version: '3.8'

services:
  web:
  build: .
  ports: 
    - "8080:8080"
  environment:
    - MYSQL_PASSWORD=${root123}

  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${root123}"
      MYSQL_DATABASE: "group4"
    volumes:
      - db-data:/var/lib/mysql

# Cache
  cache:
    image: your-cache-image
    # Add configurations for cache service

  # Processing + Like-batcher
  processing:
    image: your-processing-image
    # Add configurations for processing service

  # Redis database
  redis:
    image: redis:latest
    # Add configurations for Redis service

volumes:
  db_data:
