version: '3.1'

services:
  web:
  build: .
  ports: 
    - "8080:8080"
  db:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/foo

# Cache
  cache:
    image: your-cache-image
    # Add configurations for cache service

  # Processing + Like-batcher
  processing:
    image: your-processing-image
    # Add configurations for processing service

  # SQL database
  database:
    image: mysql:latest  # Example MySQL image
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: your_database_name
    volumes:
      - db_data:/var/lib/mysql

  # Redis database
  redis:
    image: redis:latest
    # Add configurations for Redis service

volumes:
  db_data:
