version: '3'

services:

  # SQL database
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redditdb
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro

  # processing layer/API Flask app
  processing:
    image: flaskapplication:latest
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db