# version: '3'

# services:
#   # processing layer/API FastAPI app
#   processing:
#     build: ./app
#     image: fastapiapplication:latest
#     environment:
#       FASTAPI_ENV: development
#     depends_on:
#       - db
#     deploy:
#       replicas: 3
#     networks:
#       - app-network

#   # SQL database
#   db:
#     image: mysql:latest
#     restart: always
#     ports:
#       - "5002:5000"
#     environment:
#       MYSQL_ROOT_PASSWORD: "root123"
#       MYSQL_USER: "group4"
#       MYSQL_PASSWORD: "root123"
#       MYSQL_DATABASE: "redditdb"
#     volumes:
#       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
#       - ./data:/var/lib/mysql
#     networks:
#       - app-network

#   # Nginx load balancer
#   nginx:
#     image: nginx:alpine
#     ports:
#       - "8000:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - processing
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

version: '3'

services:
  # processing layer/API FastAPI app
  processing:
    build: ./app
    image: fastapiapplication:latest
    environment:
      FASTAPI_ENV: development
    depends_on:
      - db
    networks:
      - app-network

  processing_1:
    build: ./app
    image: fastapiapplication:latest
    environment:
      FASTAPI_ENV: development
    depends_on:
      - db
    networks:
      - app-network

  processing_2:
    build: ./app
    image: fastapiapplication:latest
    environment:
      FASTAPI_ENV: development
    depends_on:
      - db
    networks:
      - app-network

  # SQL database
  db:
    image: mysql:latest
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_USER: "group4"
      MYSQL_PASSWORD: "root123"
      MYSQL_DATABASE: "redditdb"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
    networks:
      - app-network

  # Nginx load balancer
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - processing
      - processing_1
      - processing_2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
