version: '3'

services:

  db:
    container_name: sqldb
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - "./database:/docker-entrypoint-initdb.d/:ro"

  # processing layer/API Flask app
  processing:
    container_name: flaskapp
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
        - db
    environment:
      DB_HOST: localhost
      DB_USER: group4
      DB_PASSWORD: root123
      DB_NAME: fakeredditdb

networks:
  app-network:
    driver: bridge
