version: '3'

services:

  db:
    image: mysql:5.7
    container_name: sqldb
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro
    networks:
      - app-network

  # processing layer/API Flask app
  processing:
    container_name: flaskapp
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
        - db

networks:
  app-network:
    driver: bridge
