version: '3'

services:
  # processing layer/API Flask app
  processing:
    image: flaskapplication:latest
    build: ./app
    links:
      - db
    ports:
      - "5002:5000"
    depends_on:
      - db
    environment: #variable to set to developmnent
      FLASK_ENV: development

  # SQL database
  db:
    image: mysql:latest
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_USER: "group4"
      MYSQL_PASSWORD: "root123"
      MYSQL_DATABASE: "redditdb"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql


