version: '3'

services:
  # processing layer/API Flask app
  processing:
    build: ./app
    links:
      - db
    ports:
      - "5001:5000"
    depends_on:
      - db

  # SQL database
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "group4"
      MYSQL_PASSWORD: "root123"
      MYSQL_DATABASE: "redditdb"
    volumes:
      - ./data:/var/lib/mysql


