version: '3'

services:

  # SQL database
  #db:
   # image: mysql:5.7
    #ports:
     # - "32000:3306"
    #environment:
     # MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: redditdb
    #volumes:
     # - ./database:/docker-entrypoint-initdb.d/:ro

  # processing layer/API Flask app
  processing:
    container_name: flaskapp
    build:
      context: ./app
      dockerfile: Dockerfile
    #links:
     # - db
    ports:
      - "5003:5000"
    networks:
      - app-network
    #depends_on:
     # - db

networks:
  app-network:
    driver: bridge