version: '3'

services:

  db:
    container_name: sqldb
    image: mariadb:10.5
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fakeredditdb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # processing layer/API Flask app
  processing:
    container_name: flaskapp
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
        - db

networks:
  app-network:
    driver: bridge
