version: '3'

services:
  processing:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: fastapiapplication:latest
    environment:
      FASTAPI_ENV: development
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
